language: node_js
node_js:
- 13

services:
- docker

# Prétester les installations
install:
- echo "nothing needs to be installed"

# Scripts à exécuter en guise de tests
before_script:
- echo "no tests"

script:
- docker --version # print the version for logging
- docker build -t udagram-api-feed ./udagram-api-feed
- docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:latest
- docker build -t udagram-api-user ./udagram-api-user
- docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:latest
- docker build -t frontend ./udagram-frontend
- docker tag frontend "$DOCKER_USERNAME"/udagram-frontend
- docker build -t reverseproxy:v5 ./udagram-reverseproxy
- docker tag reverseproxy:v5 "$DOCKER_USERNAME"/reverseproxy:v5


after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_USERNAME"/udagram-api-feed
- docker push "$DOCKER_USERNAME"/udagram-api-user
- docker push "$DOCKER_USERNAME"/udagram-frontend
- docker push "$DOCKER_USERNAME"/reverseproxy:v5
