apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QVNJQVFXS0dPSk5JUUlaTTdLTU0=
  aws_secret_access_key: OUtMT3FxcmJocC92SDBYRUpNRjY5a3B3M2FSSlBuTnNPZXhkSnFSVA==
  aws_session_token: RndvR1pYSXZZWGR6RU1ULy8vLy8vLy8vL3dFYURDRUhQdks0OThrZENDL01saUxWQVVTUCs4OXdyckFrdmtuQjNLcXBlblowWExLUUxMUkRDZTNYcW9ORkl4VjlRK0FiZ0V2Q0ZsT1VRZms1dVh0cmZqKzM3Skh0bFFzN1FnaU1RUjE0aXhOZzFZSzV6SGpJRTJ1WlRqckpUYjBqZ1lMV3pRQlI4UktlZkVCSmZySFJSd2ZrK294WEpUT2p6WnlsRHFHWllvV09SVU9uQXF3d24xNDNjSzQyb01jaFVuWEhvOForait1WVJkTkxubjNXTlVOZTg0MVVMNG1mQXo0TlJYM0lGMzhHbm9lY3FOT3ZLLzJDRlBXTW5VRDVManpOdkpkS3JZQXNqSG1VbWRZQnJhempVQ1Y3Tmp0VExFUXl3eTVqZWJ2ZEpoSzRIQ2pRdDZhWkJqSXRQVjZ2MjFPSVhaSzFrWHltTzZlLzQ0eXBLa3cxYlFzb3NZMG1zcktLOEg0Z1dNV2lCWHFacGRlU1FZY0c=
