apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed-deployment
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: thimotee/udagram-api-feed
        ports:
        - containerPort: 8080
        env:
        - name: aws_access_key_id
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id
        - name: aws_secret_access_key
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key
        - name: aws_session_token
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_session_token
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: micro-config
              key: URL